### ISSUE TITLE
请问支持集群功能吗？

### ISSUE THREAD

**Issue by peteyan** [skddyj/rdm-web#1]
你好，我看到截图中的集群功能，请问源码中开放出来了吗？非常感谢！

**Comment by skddyj** [comment]
你好，因为最近一直比较忙，集群功能暂时还没开发

**Comment by skddyj** [comment]
> 你好，我看到截图中的集群功能，请问源码中开放出来了吗？非常感谢！

你好，集群功能已经放出来了，可以试用一下，有问题可以提issue
